-- Fill the agent table.
-- "agentID","agentRemarks","agentType","preferredAgentName"
INSERT INTO agent (
    agent_id,
    agent_remarks,
    agent_type,
    preferred_agent_name
)
(
SELECT
  agentID AS agent_id,
  agentRemarks AS agent_remarks,
  agentType AS agent_type,
  preferredAgentName as preferred_agent_name
FROM input_agent
);
-- n = 155

-- Fill the media table.
-- "accessURI","available","caption","captureDevice","collectionCode","collectionID",
-- "commenterID","commenterLiteral","comments","CreateDate","derivedFromMediaID",
-- "description","digitizationDate","endTime","endTimestamp","format","formatIRI",
-- "frameRate","freqHigh","freqLow","furtherInformationURL","hashFunction","hashValue",
-- "hasServiceAccessPoint","heightFrac","isPartOfMediaID","language","languageIRI",
-- "mediaDuration","mediaID","mediaSpeed","mediaType","MetadataDate",
-- "metadataLanguageIRI","metadataLanguageLiteral","modified","physicalSetting",
-- "PixelXDimension","PixelYDimension","providerManagedID","radius","Rating",
-- "resourceCreationTechnique","reviewerComments","reviewerID","reviewerLiteral",
-- "sample_rate","serviceExpectation","startTime","startTimestamp","subjectCategory",
-- "subjectCategoryIRI","subjectCategorySource","subjectOrientationIRI",
-- "subjectOrientationLiteral","subjectPartIRI","subjectPartLiteral","subtypeIRI",
-- "subtypeLiteral","tag","timeOfDay","title","variantDescription","variantIRI",
-- "variantLiteral","widthFrac","xFrac","yFrac"
INSERT INTO media (
    access_uri,
    available,
    caption,
    capture_device,
    collection_code,
    collection_id,
    commenter_id,
    commenter_literal,
    comments,
    create_date,
    derived_from_media_id,
    description,
    digitization_date,
    end_time,
    end_timestamp,
    format,
    format_iri,
    frame_rate,
    freq_high,
    freq_low,
    further_information_url,
    hash_function,
    hash_value,
    has_service_access_point,
    height_frac,
    is_part_of_media_id,
    language,
    language_iri,
    media_duration,
    media_id,
    media_speed,
    media_type,
    metadata_date,
    metadata_language_iri,
    metadata_language_literal,
    modified,
    physical_setting,
    pixel_x_dimension,
    pixel_y_dimension,
    provider_managed_id,
    radius,
    rating,
    resource_creation_technique,
    reviewer_comments,
    reviewer_id,
    reviewer_literal,
    sample_rate,
    service_expectation,
    start_time,
    start_timestamp,
    subject_category,
    subject_category_iri,
    subject_category_source,
    subject_orientation_iri,
    subject_orientation_literal,
    subject_part_iri,
    subject_part_literal,
    subtype_iri,
    subtype_literal,
    tag,
    time_of_day,
    title,
    variant_description,
    variant_iri,
    variant_literal,
    width_frac,
    x_frac,
    y_frac
)
(
SELECT
    accessURI AS access_uri,
    available AS available,
    caption AS caption,
    captureDevice AS capture_device,
    collectionCode AS collection_code,
    collectionID AS collection_id,
    commenterID AS commenter_id,
    commenterLiteral AS commenter_literal,
    comments AS comments,
    CreateDate AS create_date,
    derivedFromMediaID AS derived_from_media_id,
    description AS description,
    digitizationDate AS digitization_date,
    endTime AS end_time,
    endTimestamp AS end_timestamp,
    format AS format,
    formatIRI AS format_iri,
    frameRate AS frame_rate,
    freqHigh AS freq_high,
    freqLow AS freq_low,
    furtherInformationURL AS further_information_url,
    hashFunction AS hash_function,
    hashValue AS hash_value,
    hasServiceAccessPoint AS has_service_access_point,
    heightFrac AS height_frac,
    isPartOfMediaID AS is_part_of_media_id,
    language AS language,
    languageIRI AS language_iri,
    mediaDuration AS media_duration,
    mediaID AS media_id,
    mediaSpeed AS media_speed,
    mediaType AS media_type,
    MetadataDate AS metadata_date,
    metadataLanguageIRI AS metadata_language_iri,
    metadataLanguageLiteral AS metadata_language_literal,
    modified AS modified,
    physicalSetting AS physical_setting,
    PixelXDimension AS pixel_x_dimension,
    PixelYDimension AS pixel_y_dimension,
    providerManagedID AS provider_managed_id,
    radius AS radius,
    Rating AS rating,
    resourceCreationTechnique AS resource_creation_technique,
    reviewerComments AS reviewer_comments,
    reviewerID AS reviewer_id,
    reviewerLiteral AS reviewer_literal,
    sample_rate AS sample_rate,
    serviceExpectation AS service_expectation,
    startTime AS start_time,
    startTimestamp AS start_timestamp,
    subjectCategory AS subject_category,
    subjectCategoryIRI AS subject_category_iri,
    subjectCategorySource AS subject_category_source,
    subjectOrientationIRI AS subject_orientation_iri,
    subjectOrientationLiteral AS subject_orientation_literal,
    subjectPartIRI AS subject_part_iri,
    subjectPartLiteral AS subject_part_literal,
    subtypeIRI AS subtype_iri,
    subtypeLiteral AS subtype_literal,
    tag AS tag,
    timeOfDay AS time_of_day,
    title AS title,
    variantDescription AS variant_description,
    variantIRI AS variant_iri,
    variantLiteral AS variant_literal,
    widthFrac AS width_frac,
    xFrac AS x_frac,
    yFrac AS y_frac
FROM input_media
);
-- n = 165

-- Fill the usage_policy table.
-- "accessRights","attributionLinkURL","attributionLogoURL","credit","license",
-- "licenseLogoURL","licensingException","owner","ownerID","rights","rightsHolder",
-- "rightsHolderID","rightsIRI","usagePolicyID","usageTerms","webStatement"
INSERT INTO usage_policy (
  access_rights,
  attribution_link_url,
  attribution_logo_url,
  credit,
  license,
  license_logo_url,
  licensing_exception,
  owner,
  owner_id,
  rights,
  rights_holder,
  rights_holder_id,
  rights_iri,
  usage_policy_id,
  usage_terms,
  web_statement
)
(
SELECT
  accessRights AS access_rights,
  attributionLinkURL AS attribution_link_url,
  attributionLogoURL AS attribution_logo_url,
  credit AS credit,
  license AS license,
  licenseLogoURL AS license_logo_url,
  licensingException AS licensing_exception,
  owner AS owner,
  ownerID AS owner_id,
  rights AS rights,
  rightsHolder AS rights_holder,
  rightsHolderID AS rights_holder_id,
  rightsIRI AS rights_iri,
  usagePolicyID AS usage_policy_id,
  usageTerms AS usage_terms,
  webStatement AS web_statement
FROM input_usage_policy
);
-- n = 2

-- Fill the media_usage_policy table.
-- "mediaID","usagePolicyID"
INSERT INTO media_usage_policy (
    media_id,
    usage_policy_id
)
(
SELECT
    mediaID AS media_id,
    usagePolicyID AS usage_policy_id
FROM input_media_usage_policy
);
-- n = 165

-- Fill the event table.
-- "continent","coordinatePrecision","coordinateUncertaintyInMeters","country",
-- "countryCode","county","datasetID","datasetName","day","decimalLatitude",
-- "decimalLongitude","endDayOfYear","eventCategory","eventConductedBy",
-- "eventConductedByID","eventDate","eventEffort","eventID","eventReferences",
-- "eventRemarks","eventTime","eventType","fieldNotes","fieldNumber",
-- "footprintSpatialFit","footprintSRS","footprintWKT","geodeticDatum","georeferencedBy",
-- "georeferencedByID","georeferencedDate","georeferenceProtocol",
-- "georeferenceProtocolID","georeferenceRemarks","georeferenceSources",
-- "georeferenceVerificationStatus","habitat","higherGeography","higherGeographyID",
-- "island","islandGroup","locality","locationID","locationRemarks",
-- "maximumDepthInMeters","maximumDistanceAboveSurfaceInMeters",
-- "maximumElevationInMeters","minimumDepthInMeters",
-- "minimumDistanceAboveSurfaceInMeters","minimumElevationInMeters","month",
-- "municipality","parentEventID","pointRadiusSpatialFit","preferredEventName",
-- "preferredSpatialRepresentation","siteNumber","startDayOfYear","stateProvince",
-- "verbatimCoordinates","verbatimCoordinateSystem","verbatimDepth","verbatimElevation",
-- "verbatimEventDate","verbatimLatitude","verbatimLocality","verbatimLongitude",
-- "verbatimSRS","verticalDatum","waterBody","year"
INSERT INTO event (
    continent,
    coordinate_precision,
    coordinate_uncertainty_in_meters,
    country, 
    country_code, 
    county, 
    dataset_id,
    dataset_name,
    day,
    decimal_latitude, 
    decimal_longitude, 
    end_day_of_year,
    event_category, 
    event_conducted_by, 
    event_conducted_by_id,
    event_date, 
    event_effort, 
    event_id, 
    event_references, 
    event_remarks,
    event_time, 
    event_type, 
    field_notes,
    field_number,
    footprint_spatial_fit,
    footprint_srs,
    footprint_wkt,
    geodetic_datum, 
    georeferenced_by,
    georeferenced_by_id,
    georeferenced_date,
    georeference_protocol,
    georeference_protocol_id,
    georeference_remarks,
    georeference_sources,
    georeference_verification_status,
    habitat,
    higher_geography,
    higher_geography_id,
    island,
    island_group,
    locality, 
    location_id, 
    location_remarks, 
    maximum_depth_in_meters,
    maximum_distance_above_surface_in_meters,
    maximum_elevation_in_meters,
    minimum_depth_in_meters,
    minimum_distance_above_surface_in_meters,
    minimum_elevation_in_meters,
    month,
    municipality,
    parent_event_id,
    point_radius_spatial_fit,
    preferred_event_name,
    preferred_spatial_representation,
    site_number,
    start_day_of_year,
    state_province,
    verbatim_coordinates, 
    verbatim_coordinate_system,
    verbatim_depth,
    verbatim_elevation, 
    verbatim_event_date,
    verbatim_latitude,
    verbatim_locality,
    verbatim_longitude,
    verbatim_srs,
    vertical_datum,
    water_body,
    year 
)
(
SELECT
  continent AS continent,
  coordinatePrecision AS coordinate_precision,
  coordinateUncertaintyInMeters AS coordinate_uncertainty_in_meters,
  country AS country,
  countryCode AS country_code,
  county AS county,
  datasetID AS dataset_id,
  datasetName AS dataset_name,
  day AS day,
  decimalLatitude AS decimal_latitude,
  decimalLongitude AS decimal_longitude,
  endDayOfYear AS end_day_of_year,
  eventCategory AS event_category,
  eventConductedBy AS event_conducted_by,
  eventConductedByID AS event_conducted_by_id,
  eventDate AS event_date,
  eventEffort AS event_effort,
  eventID AS event_id,
  eventReferences AS event_references,
  eventRemarks AS event_remarks,
  eventTime AS event_time,
  eventType AS event_type,
  fieldNotes AS field_notes,
  fieldNumber AS field_number,
  footprintSpatialFit AS footprint_spatial_fit,
  footprintSRS AS footprint_srs,
  footprintWKT AS footprint_wkt,
  geodeticDatum AS geodetic_datum,
  georeferencedBy AS georeferenced_by,
  georeferencedByID AS georeferenced_by_id,
  georeferencedDate AS georeferenced_date,
  georeferenceProtocol AS georeference_protocol,
  georeferenceProtocolID AS georeference_protocol_id,
  georeferenceRemarks AS georeference_remarks,
  georeferenceSources AS georeference_sources,
  georeferenceVerificationStatus AS georeference_verification_status,
  habitat AS habitat,
  higherGeography AS higher_geography,
  higherGeographyID AS higher_geography_id,
  island AS island,
  islandgroup AS island_group,
  locality AS locality,
  locationID AS locality_id,
  locationRemarks AS location_remarks,
  maximumDepthInMeters AS maximum_depth_in_meters,
  maximumDistanceAboveSurfaceInMeters AS maximum_distance_above_surface_in_meters,
  maximumElevationInMeters AS maximum_elevation_in_meters,
  minimumDepthInMeters AS minimum_depth_in_meters,
  minimumDistanceAboveSurfaceInMeters AS minimum_distance_above_surface_in_meters,
  minimumElevationInMeters AS minimum_elevation_in_meters,
  month AS month,
  municipality AS municipality,
  NULLIF(parentEventID, '')::TEXT AS parent_event_id,
  pointRadiusSpatialFit AS point_radius_spatial_fit,
  preferredEventName AS preferred_event_name,
  preferredSpatialRepresentation AS preferred_spatial_representation,
  siteNumber AS site_number,
  startDayOfYear AS start_day_of_year,
  stateProvince AS state_province,
  verbatimCoordinates AS verbatim_coordinates,
  verbatimCoordinateSystem AS verbatim_coordinate_system,
  verbatimDepth AS verbatim_depth,
  verbatimElevation AS verbatim_elevation,
  verbatimEventDate AS verbatim_event_date,
  verbatimLatitude AS verbatim_latitude,
  verbatimLocality AS verbatim_locality,
  verbatimLongitude AS verbatim_longitude,
  verbatimSRS AS verbatim_srs,
  verticalDatum AS vertical_datum,
  waterBody AS water_body,
  year AS year
FROM input_event
);
-- n = 289

-- Fill the occurrence table.
INSERT INTO occurrence (
    behavior,
    caste,
    cause_of_death,
    data_generalizations,
    date_identified,
    degree_of_establishment,
    establishment_means,
    event_id,
    external_classification_source,
    feedback_url,
    identification_references,
    identification_remarks,
    identification_verification_status,
    identified_by,
    identified_by_id,
    information_withheld,
    is_part_of_occurrence_id,
    life_stage,
    occurrence_id,
    occurrence_references,
    occurrence_remarks,
    occurrence_status,
    organism_id,
    organism_name,
    organism_quantity,
    organism_quantity_type,
    organism_remarks,
    organism_scope,
    pathway,
    recorded_by,
    recorded_by_id,
    reproductive_condition,
    scientific_name,
    scientific_name_authorship,
    scientific_name_id,
    sex,
    substrate,
    survey_target_id,
    taxon_id,
    taxon_rank,
    verbatim_identification,
    vernacular_name,
    vitality
)
(
SELECT
  behavior AS behavior,
  caste AS caste,
  causeOfDeath AS cause_of_death,
  dataGeneralizations AS data_generalizations,
  dateIdentified AS date_identified,
  degreeOfEstablishment AS degree_of_establishment,
  establishmentMeans AS establishment_means,
  eventID AS event_id,
  externalClassificationSource AS external_classification_source,
  feedbackURL AS feedback_url,
  identificationReferences AS identification_references,
  identificationRemarks AS identification_remarks,
  identificationVerificationStatus AS identification_verification_status,
  identifiedBy AS identified_by,
  identifiedByID AS identified_by_id,
  informationWithheld AS information_withheld,
  NULLIF(isPartOfOccurrenceID, '')::TEXT AS is_part_of_occurrence_id,
  lifeStage AS life_stage,
  occurrenceID AS occurrence_id,
  occurrenceReferences AS occurrence_references,
  occurrenceRemarks AS occurrence_remarks,
  COALESCE(NULLIF(occurrencestatus, ''), 'detected')::OCCURRENCE_STATUS AS occurrence_status,
  organismID AS organism_id,
  organismName AS organism_name,
  organismQuantity AS organism_quantity,
  organismQuantityType AS organism_quantity_type,
  organismRemarks AS organism_remarks,
  organismScope AS organism_scope,
  pathway AS pathway,
  recordedBy AS recorded_by,
  recordedByID AS recorded_by_id,
  reproductiveCondition AS reproductive_condition,
  scientificName AS scietific_name,
  scientificNameAuthorship AS scientific_name_authorship,
  scientificNameID AS scientific_name_id,
  sex AS sex,
  substrate AS substrate,
  surveyTargetID AS survey_target_id,
  taxonID AS taxon_id,
  taxonRank AS taxon_rank,
  verbatimIdentification AS verbatim_identification,
  vernacularName AS vernacular_name,
  vitality AS vitality
FROM input_occurrence
);
-- n = 287

-- Fill the material table.
INSERT INTO material (
    associated_sequences,
    catalog_number,
    collected_by,
    collected_by_id,
    collection_code,
    collection_id,
    collector_number,
    data_generalizations,
    date_identified,
    derivation_event_id,
    derivation_type,
    derived_from_material_entity_id,
    digital_specimen_id,
    discipline,
    disposition,
    event_id,
    evidence_for_occurrence_id,
    external_classification_source,
    feedback_url,
    geo_classification_code,
    geo_name,
    identification_references,
    identification_remarks,
    identification_verification_status,
    identified_by,
    identified_by_id,
    information_withheld,
    institution_code,
    institution_id,
    is_part_of_material_entity_id,
    material_category,
    material_entity_id,
    material_entity_remarks,
    material_entity_type,
    material_references,
    object_quantity,
    object_quantity_type,
    other_catalog_numbers,
    owner_institution_code,
    owner_institution_id,
    preparations,
    scientific_name,
    scientific_name_authorship,
    scientific_name_id,
    taxon_id,
    taxon_rank,
    type_designation_type,
    type_status,
    typified_name,
    verbatim_identification,
    verbatim_label,
    vernacular_name
)
(
SELECT 
  associatedSequences AS associated_sequences,
  catalogNumber AS catalog_number,
  collectedBy AS collected_by,
  collectedByID AS collected_by_id,
  collectionCode AS collection_code,
  collectionID AS collection_id,
  collectorNumber AS collector_number,
  dataGeneralizations AS data_generalizations,
  dateIdentified AS date_identified,
  derivationEventID AS derivation_event_id,
  derivationType AS derivation_type,
  derivedFromMaterialEntityID AS derived_from_material_entity_id,
  digitalSpecimenID AS digital_specimen_id,
  discipline AS discipline,
  disposition AS disposition,
  eventID AS event_id,
  evidenceForOccurrenceID AS evidence_for_occurrence_id,
  externalClassificationSource AS external_classification_source,
  feedbackURL AS feedback_url,
  geoClassificationCode AS geo_classification_code,
  geoName AS geo_name,
  identificationReferences AS identification_references,
  identificationRemarks AS identification_remarks,
  identificationVerificationStatus AS identification_verification_status,
  identifiedBy AS identified_by,
  identifiedByID AS identified_by_id,
  informationWithheld AS information_withheld,
  institutionCode AS institution_code,
  institutionID AS institution_id,
  isPartOfMaterialEntityID AS is_part_of_material_entity_id,
  materialCategory AS material_category,
  materialEntityID AS material_entity_id,
  materialEntityRemarks AS material_entity_remarks,
  materialEntityType AS material_entity_type,
  materialReferences AS material_references,
  objectQuantity AS object_quantity,
  objectQuantityType AS object_quantity_type,
  otherCatalogNumbers AS other_catalog_numbers,
  ownerInstitutionCode AS owner_institution_code,
  ownerInstitutionID AS owner_institution_id,
  preparations AS preparations,
  scientificName AS scientific_name,
  scientificNameAuthorship AS scientific_name_authorship,
  scientificNameID AS scientific_name_id,
  taxonID AS taxon_id,
  taxonRank AS taxon_rank,
  typeDesignationType AS type_designation_type,
  typeStatus AS type_status,
  typifiedName AS typified_name,
  verbatimIdentification AS verbatim_identification,
  verbatimLabel AS verbatim_label,
  vernacularName AS vernacular_name
FROM input_material
);
-- n = 300

-- Fill the material_media table.
INSERT INTO material_media (
    material_entity_id,
    media_id,
    physical_setting,
    subject_category,
    subject_category_iri,
    subject_category_source,
    subject_orientation,
    subject_orientation_literal,
    subject_part,
    subject_part_literal
)
(
SELECT
  materialEntityID AS material_entity_id,
  mediaID AS media_id,
  physicalSetting AS physical_setting,
  subjectCategory AS subject_category,
  subjectCategoryIRI AS subject_category_iri,
  subjectCategorySource AS subject_category_source,
  subjectOrientation AS subject_orientation,
  subjectOrientationLiteral AS subject_orientation_literal,
  subjectPart AS subject_part,
  subjectPartLiteral AS subject_part_literal
FROM input_material_media
);
-- n = 165

-- Fill the material_usage_policy table.
INSERT INTO material_usage_policy (
  material_entity_id,
  usage_policy_id
)
(
SELECT
  materialEntityID AS material_entity_id,
  usagePolicyID AS usage_policy_id
FROM input_material_usage_policy
);
-- n = 300

-- Fill the identification table.
INSERT INTO identification (
    class,
    cultivar_epithet,
    date_identified,
    external_classification_source,
    family,
    feedback_url,
    generic_name,
    genus,
    geo_classification_code,
    geo_name,
    identification_id,
    identification_references,
    identification_remarks,
    identification_verification_status,
    identified_by,
    identified_by_id,
    infrageneric_epithet,
    infraspecific_epithet,
    is_accepted_identification,
    kingdom,
    material_entity_id,
    media_id,
    name_according_to,
    name_published_in,
    name_published_in_year,
    nomenclatural_code,
    nomenclatural_status,
    nucleotide_analysis_id,
    nucleotide_sequence_id,
    occurrence_id,
    "order",
    organism_id,
    phylum,
    scientific_name,
    scientific_name_authorship,
    scientific_name_id,
    specific_epithet,
    subfamily,
    subgenus,
    taxon_assignment_method,
    taxon_formula,
    taxon_id,
    taxon_rank,
    taxon_remarks,
    type_designation_type,
    type_status,
    verbatim_identification,
    vernacular_name
)
(
SELECT
  clazz AS class,
  cultivarEpithet AS cultivar_epithet,
  dateIdentified AS date_identified,
  externalClassificationSource AS external_classification_source,
  family AS family,
  feedbackURL AS feedback_url,
  genericName AS generic_name,
  genus AS genus,
  geoClassificationCode AS geo_classification_code,
  geoName AS geo_name,
  identificationID AS identification_id,
  identificationReferences AS identification_reference,
  identificationRemarks AS identification_remarks,
  identificationVerificationStatus AS identification_verification_status,
  identifiedBy AS identified_by,
  identifiedByID AS identified_by_id,
  infragenericEpithet AS infrageneric_epithet,
  infraspecificEpithet AS infraspecific_epithet,
  NULLIF(isAcceptedIdentification, '')::BOOLEAN AS is_accepted_identification,
  kingdom AS kingdom,
  materialEntityID AS material_entity_id,
  mediaID AS media_id,
  nameAccordingTo AS name_according_to,
  namePublishedIn AS name_published_in,
  namePublishedInYear AS name_published_in_year,
  nomenclaturalCode AS nomenclatural_code,
  nomenclaturalStatus AS nomenclatural_status,
  nucleotideAnalysisID AS nucleotide_analysis_id,
  nucleotideSequenceID AS nucleotide_sequence_id,
  occurrenceID AS occurrence_id,
  "order" AS "order",
  organismID AS organism_id,
  phylum AS phylum,
  scientificName AS scientific_name,
  scientificNameAuthorship AS scientific_name_authorship,
  scientificNameID AS scientific_name_id,
  specificEpithet AS specific_epithet,
  subfamily AS subfamily,
  subgenus AS subgenus,
  taxonAssignmentMethod AS taxon_assignment_method,
  taxonFormula AS taxon_formula,
  taxonID AS taxon_id,
  taxonRank AS taxon_rank,
  taxonRemarks AS taxon_remarks,
  typeDesignationType AS type_designation_type,
  typeStatus AS type_status,
  verbatimIdentification AS veratim_verification_status,
  vernacularName AS vernacular_name
FROM input_identification
);
-- n = 300

-- Fill the identification_agent_role table.
INSERT INTO identification_agent_role (
    agent_id,
    agent_role,
    agent_role_date,
    agent_role_iri,
    agent_role_order,
    agent_role_source,
    identification_id
)
(
SELECT
  agentID AS agent_id,
  agentRole AS agent_role,
  agentRoleDate AS agent_role_date,
  agentRoleIRI AS agent_role_iri,
  COALESCE(agentRoleOrder, 1) AS agent_role_order,
  agentRoleSource AS agent_role_source,
  identificationID AS identification_id
FROM input_identification_agent_role
);
-- n = 1

-- Fill the identification_taxon table.
INSERT INTO identification_taxon (
    class,
    cultivar_epithet,
    external_classification_source,
    family,
    generic_name,
    genus,
    geo_classification_code,
    geo_name,
    identification_id,
    infrageneric_epithet,
    infraspecific_epithet,
    kingdom,
    name_according_to,
    name_published_in,
    name_published_in_year,
    nomenclatural_code,
    nomenclatural_status,
    "order",
    phylum,
    scientific_name,
    scientific_name_authorship,
    scientific_name_id,
    specific_epithet,
    subfamily,
    subgenus,
    taxon_id,
    taxon_rank,
    taxon_sort_order,
    vernacular_name
)
(
SELECT
  class AS class,
  cultivarEpithet AS cultivar_epithet,
  externalClassificationSource AS external_classification_source,
  family AS family,
  genericName AS generic_name,
  genus AS genus,
  geoClassificationCode AS geo_classification_code,
  geoName AS geo_name,
  identificationID AS identification_id,
  infragenericEpithet AS infrageneric_epithet,
  infraspecificEpithet AS infraspecific_epithet,
  kingdom AS kingdom,
  nameAccordingTo AS name_according_to,
  namePublishedIn AS name_published_in,
  namePublishedInYear AS name_published_in_year,
  nomenclaturalCode AS nomenclatural_code,
  nomenclaturalStatus AS nomenclatural_status,
  "order" AS "order",
  phylum AS phylum,
  scientificName AS scientific_name,
  scientificNameAuthorship AS scientific_name_authorship,
  scientificNameID AS scientific_name_id,
  specificEpithet AS specific_epithet,
  subfamily AS subfamily,
  subgenus AS subgenus,
  taxonID AS taxon_id,
  taxonRank AS taxon_rank,
  COALESCE(taxonSortOrder, 1) AS taxon_sort_order,
  vernacularName AS vernacular_name
FROM input_identification_taxon
);
-- n = 272
