---
-- Schema for input data to be mapped to dwc-dp publishing model.
--

-- "agentID","agentRemarks","agentType","preferredAgentName"
CREATE TABLE input_agent (
  agentID TEXT PRIMARY KEY,
  agentRemarks TEXT,
  agentType TEXT NOT NULL,
  preferredAgentName TEXT
);

-- "agentID","agentRole","agentRoleDate","agentRoleIRI","agentRoleOrder",
-- "agentRoleVocabulary","eventID"
CREATE TABLE input_event_agent_role (
  agentID TEXT NOT NULL,
  agentRole TEXT NOT NULL,
  agentRoleDate TEXT,
  agentRoleIRI TEXT,
  agentRoleOrder TEXT,
  agentRoleVocabulary TEXT,
  eventID TEXT NOT NULL
);

-- "continent","coordinatePrecision","coordinateUncertaintyInMeters","country",
-- "countryCode","county","datasetID","datasetName","day","decimalLatitude",
-- "decimalLongitude","endDayOfYear","eventCategory","eventConductedBy",
-- "eventConductedByID","eventDate","eventEffort","eventID","eventReferences",
-- "eventRemarks","eventTime","eventType","fieldNotes","fieldNumber",
-- "footprintSpatialFit","footprintSRS","footprintWKT","geodeticDatum","georeferencedBy",
-- "georeferencedByID","georeferencedDate","georeferenceProtocol",
-- "georeferenceProtocolID","georeferenceRemarks","georeferenceSources",
-- "georeferenceVerificationStatus","habitat","higherGeography","higherGeographyID",
-- "island","islandGroup","locality","locationID","locationRemarks",
-- "maximumDepthInMeters","maximumDistanceAboveSurfaceInMeters",
-- "maximumElevationInMeters","minimumDepthInMeters",
-- "minimumDistanceAboveSurfaceInMeters","minimumElevationInMeters","month",
-- "municipality","parentEventID","pointRadiusSpatialFit","preferredEventName",
-- "preferredSpatialRepresentation","siteNumber","startDayOfYear","stateProvince",
-- "verbatimCoordinates","verbatimCoordinateSystem","verbatimDepth","verbatimElevation",
-- "verbatimEventDate","verbatimLatitude","verbatimLocality","verbatimLongitude",
-- "verbatimSRS","verticalDatum","waterBody","year"
CREATE TABLE input_event (
  continent TEXT,
  coordinatePrecision NUMERIC,
  coordinateUncertaintyInMeters NUMERIC,
  country TEXT,
  countryCode CHAR(2),
  county TEXT,
  datasetID TEXT,
  datasetName TEXT,
  day SMALLINT,
  decimalLatitude NUMERIC,
  decimalLongitude NUMERIC,
  endDayOfYear SMALLINT,
  eventCategory TEXT,
  eventConductedBy TEXT,
  eventConductedByID TEXT,
  eventDate TEXT,
  eventEffort TEXT,
  eventID TEXT PRIMARY KEY,
  eventReferences TEXT,
  eventRemarks TEXT,
  eventTime TEXT,
  eventType TEXT,
  fieldNotes TEXT,
  fieldNumber TEXT,
  footprintSpatialFit NUMERIC,
  footprintSRS TEXT,
  footprintWKT TEXT,
  geodeticDatum TEXT,
  georeferencedBy TEXT,
  georeferencedByID TEXT,
  georeferencedDate TEXT,
  georeferenceProtocol TEXT,
  georeferenceProtocolID TEXT,
  georeferenceRemarks TEXT,
  georeferenceSources TEXT,
  georeferenceVerificationStatus TEXT,
  habitat TEXT,
  higherGeography TEXT,
  higherGeographyID TEXT,
  island TEXT,
  islandgroup TEXT,
  locality TEXT,
  locationID TEXT,
  locationRemarks TEXT,
  maximumDepthInMeters NUMERIC,
  maximumDistanceAboveSurfaceInMeters NUMERIC,
  maximumElevationInMeters NUMERIC,
  minimumDepthInMeters NUMERIC,
  minimumDistanceAboveSurfaceInMeters NUMERIC,
  minimumElevationInMeters NUMERIC,
  month SMALLINT,
  municipality TEXT,
  parentEventID TEXT,
  pointRadiusSpatialFit NUMERIC,
  preferredEventName TEXT,
  preferredSpatialRepresentation TEXT,
  siteNumber TEXT,
  startDayOfYear SMALLINT,
  stateProvince TEXT,
  verbatimCoordinates TEXT,
  verbatimCoordinateSystem TEXT,
  verbatimDepth TEXT,
  verbatimElevation TEXT,
  verbatimEventDate TEXT,
  verbatimLatitude TEXT,
  verbatimLocality TEXT,
  verbatimLongitude TEXT,
  verbatimSRS TEXT,
  verticalDatum TEXT,
  waterBody TEXT,
  year SMALLINT
);

-- "agentID","agentRole","agentRoleDate","agentRoleIRI","agentRoleOrder","agentRoleSource","identificationID"
CREATE TABLE input_identification_agent_role (
  agentID TEXT NOT NULL,
  agentRole TEXT NOT NULL,
  agentRoleDate TEXT,
  agentRoleIRI TEXT,
  agentRoleOrder INTEGER,
  agentRoleSource TEXT,
  identificationID TEXT
);

-- "class","cultivarEpithet","externalClassificationSource","family","genericName",
-- "genus","geoClassificationCode","geoName","identificationID","infragenericEpithet",
-- "infraspecificEpithet","kingdom","nameAccordingTo","namePublishedIn",
-- "namePublishedInYear","nomenclaturalCode","nomenclaturalStatus","order","phylum",
-- "scientificName","scientificNameAuthorship","scientificNameID","specificEpithet",
-- "subfamily","subgenus","taxonID","taxonRank","taxonSortOrder","vernacularName"
CREATE TABLE input_identification_taxon (
  class TEXT,
  cultivarEpithet TEXT,
  externalClassificationSource TEXT,
  family TEXT,
  genericName TEXT,
  genus TEXT,
  geoClassificationCode TEXT,
  geoName TEXT,
  identificationID TEXT,
  infragenericEpithet TEXT,
  infraspecificEpithet TEXT,
  kingdom TEXT,
  nameAccordingTo TEXT,
  namePublishedIn TEXT,
  namePublishedInYear TEXT,
  nomenclaturalCode TEXT,
  nomenclaturalStatus TEXT,
  "order" TEXT,
  phylum TEXT,
  scientificName TEXT,
  scientificNameAuthorship TEXT,
  scientificNameID TEXT,
  specificEpithet TEXT,
  subfamily TEXT,
  subgenus TEXT,
  taxonID TEXT,
  taxonRank TEXT,
  taxonSortOrder INTEGER,
  vernacularName TEXT
);

-- "clazz","cultivarEpithet","dateIdentified","externalClassificationSource","family",
-- "feedbackURL","genericName","genus","geoClassificationCode","geoName",
-- "identificationID","identificationReferences","identificationRemarks",
-- "identificationVerificationStatus","identifiedBy","identifiedByID",
-- "infragenericEpithet","infraspecificEpithet","isAcceptedIdentification","kingdom",
-- "materialEntityID","mediaID","nameAccordingTo","namePublishedIn","namePublishedInYear",
-- "nomenclaturalCode","nomenclaturalStatus","nucleotideAnalysisID",
-- "nucleotideSequenceID","occurrenceID","order","organismID","phylum","scientificName",
-- "scientificNameAuthorship","scientificNameID","specificEpithet","subfamily","subgenus",
-- "taxonAssignmentMethod","taxonFormula","taxonID","taxonRank","taxonRemarks",
-- "typeDesignationType","typeStatus","verbatimIdentification","vernacularName"
CREATE TABLE input_identification (
  clazz TEXT,
  cultivarEpithet TEXT,
  dateIdentified TEXT,
  externalClassificationSource TEXT,
  family TEXT,
  feedbackURL TEXT,
  genericName TEXT,
  genus TEXT,
  geoClassificationCode TEXT,
  geoName TEXT,
  identificationID TEXT PRIMARY KEY NOT NULL,
  identificationReferences TEXT,
  identificationRemarks TEXT,
  identificationVerificationStatus TEXT,
  identifiedBy TEXT,
  identifiedByID TEXT,
  infragenericEpithet TEXT,
  infraspecificEpithet TEXT,
  isAcceptedIdentification TEXT,
  kingdom TEXT,
  materialEntityID TEXT,
  mediaID TEXT,
  nameAccordingTo TEXT,
  namePublishedIn TEXT,
  namePublishedInYear TEXT,
  nomenclaturalCode TEXT,
  nomenclaturalStatus TEXT,
  nucleotideAnalysisID TEXT,
  nucleotideSequenceID TEXT,
  occurrenceID TEXT,
  "order" TEXT,
  organismID TEXT,
  phylum TEXT,
  scientificName TEXT,
  scientificNameAuthorship TEXT,
  scientificNameID TEXT,
  specificEpithet TEXT,
  subfamily TEXT,
  subgenus TEXT,
  taxonAssignmentMethod TEXT,
  taxonFormula TEXT,
  taxonID TEXT,
  taxonRank TEXT,
  taxonRemarks TEXT,
  typeDesignationType TEXT,
  typeStatus TEXT,
  verbatimIdentification TEXT,
  vernacularName TEXT
);

-- "materialEntityID","mediaID","physicalSetting","subjectCategory","subjectCategoryIRI",
-- "subjectCategorySource","subjectOrientation","subjectOrientationLiteral","subjectPart",
-- "subjectPartLiteral"
CREATE TABLE input_material_media (
  materialEntityID TEXT NOT NULL,
  mediaID TEXT NOT NULL,
  physicalSetting TEXT,
  subjectCategory TEXT,
  subjectCategoryIRI TEXT,
  subjectCategorySource TEXT,
  subjectOrientation TEXT,
  subjectOrientationLiteral TEXT,
  subjectPart TEXT,
  subjectPartLiteral TEXT
);

-- "materialEntityID","usagePolicyID"
CREATE TABLE input_material_usage_policy (
  materialEntityID TEXT NOT NULL,
  usagePolicyID TEXT NOT NULL
);

-- "associatedSequences","catalogNumber","collectedBy","collectedByID","collectionCode",
-- "collectionID","collectorNumber","dataGeneralizations","dateIdentified",
-- "derivationEventID","derivationType","derivedFromMaterialEntityID","digitalSpecimenID",
-- "discipline","disposition","eventID","evidenceForOccurrenceID",
-- "externalClassificationSource","feedbackURL","geoClassificationCode","geoName",
-- "identificationReferences","identificationRemarks","identificationVerificationStatus",
-- "identifiedBy","identifiedByID","informationWithheld","institutionCode",
-- "institutionID","isPartOfMaterialEntityID","materialCategory","materialEntityID",
-- "materialEntityRemarks","materialEntityType","materialReferences","objectQuantity",
-- "objectQuantityType","otherCatalogNumbers","ownerInstitutionCode","ownerInstitutionID",
-- "preparations","scientificName","scientificNameAuthorship","scientificNameID",
-- "taxonID","taxonRank","typeDesignationType","typeStatus","typifiedName",
-- "verbatimIdentification","verbatimLabel","vernacularName"
CREATE TABLE input_material (
  associatedSequences TEXT,
  catalogNumber TEXT,
  collectedBy TEXT,
  collectedByID TEXT,
  collectionCode TEXT,
  collectionID TEXT,
  collectorNumber TEXT,
  dataGeneralizations TEXT,
  dateIdentified TEXT,
  derivationEventID TEXT,
  derivationType TEXT,
  derivedFromMaterialEntityID TEXT,
  digitalSpecimenID TEXT,
  discipline TEXT,
  disposition TEXT,
  eventID TEXT,
  evidenceForOccurrenceID TEXT,
  externalClassificationSource TEXT,
  feedbackURL TEXT,
  geoClassificationCode TEXT,
  geoName TEXT,
  identificationReferences TEXT,
  identificationRemarks TEXT,
  identificationVerificationStatus TEXT,
  identifiedBy TEXT,
  identifiedByID TEXT,
  informationWithheld TEXT,
  institutionCode TEXT,
  institutionID TEXT,
  isPartOfMaterialEntityID TEXT,
  materialCategory TEXT,
  materialEntityID TEXT PRIMARY KEY NOT NULL,
  materialEntityRemarks TEXT,
  materialEntityType TEXT,
  materialReferences TEXT,
  objectQuantity TEXT,
  objectQuantityType TEXT,
  otherCatalogNumbers TEXT,
  ownerInstitutionCode TEXT,
  ownerInstitutionID TEXT,
  preparations TEXT,
  scientificName TEXT,
  scientificNameAuthorship TEXT,
  scientificNameID TEXT,
  taxonID TEXT,
  taxonRank TEXT,
  typeDesignationType TEXT,
  typeStatus TEXT,
  typifiedName TEXT,
  verbatimIdentification TEXT,
  verbatimLabel TEXT,
  vernacularName TEXT
);

-- "mediaID","usagePolicyID"
CREATE TABLE input_media_usage_policy (
  mediaID TEXT NOT NULL,
  usagePolicyID TEXT NOT NULL
);

-- "accessURI","available","caption","captureDevice","collectionCode","collectionID",
-- "commenterID","commenterLiteral","comments","CreateDate","derivedFromMediaID",
-- "description","digitizationDate","endTime","endTimestamp","format","formatIRI",
-- "frameRate","freqHigh","freqLow","furtherInformationURL","hashFunction","hashValue",
-- "hasServiceAccessPoint","heightFrac","isPartOfMediaID","language","languageIRI",
-- "mediaDuration","mediaID","mediaSpeed","mediaType","MetadataDate",
-- "metadataLanguageIRI","metadataLanguageLiteral","modified","physicalSetting",
-- "PixelXDimension","PixelYDimension","providerManagedID","radius","Rating",
-- "resourceCreationTechnique","reviewerComments","reviewerID","reviewerLiteral",
-- "sample_rate","serviceExpectation","startTime","startTimestamp","subjectCategory",
-- "subjectCategoryIRI","subjectCategorySource","subjectOrientationIRI",
-- "subjectOrientationLiteral","subjectPartIRI","subjectPartLiteral","subtypeIRI",
-- "subtypeLiteral","tag","timeOfDay","title","variantDescription","variantIRI",
-- "variantLiteral","widthFrac","xFrac","yFrac"
CREATE TABLE input_media (
  accessURI TEXT,
  available TEXT,
  caption TEXT,
  captureDevice TEXT,
  collectionCode TEXT,
  collectionID TEXT,
  commenterID TEXT,
  commenterLiteral TEXT,
  comments TEXT,
  CreateDate TEXT,
  derivedFromMediaID TEXT,
  description TEXT,
  digitizationDate TEXT,
  endTime NUMERIC,
  endTimeStamp TEXT,
  format TEXT,
  formatIRI TEXT,
  frameRate NUMERIC,
  freqHigh NUMERIC,
  freqLow NUMERIC,
  furtherInformationURL TEXT,
  hashFunction TEXT,
  hashValue TEXT,
  hasServiceAccessPoint TEXT,
  heightFrac NUMERIC,
  isPartOfMediaID TEXT,
  language TEXT,
  languageIRI TEXT,
  mediaDuration NUMERIC,
  mediaID TEXT PRIMARY KEY NOT NULL,
  mediaSpeed NUMERIC,
  mediaType TEXT,
  MetadataDate TEXT,
  metadataLanguageIRI TEXT,
  metadataLanguageLiteral TEXT,
  physicalSetting TEXT,
  modified TEXT,
  PixelXDimension INTEGER,
  PixelYDimension INTEGER,
  providerManagedID TEXT,
  radius NUMERIC,
  Rating TEXT,
  resourceCreationTechnique TEXT,
  reviewerComments TEXT,
  reviewerID TEXT,
  reviewerLiteral TEXT,
  sample_rate NUMERIC,
  serviceExpectation TEXT,
  startTime NUMERIC,
  startTimestamp TEXT,
  subjectCategory TEXT,
  subjectCategoryIRI TEXT,
  subjectCategorySource TEXT,
  subjectOrientationIRI TEXT,
  subjectOrientationLiteral TEXT,
  subjectPartIRI TEXT,
  subjectPartLiteral TEXT,
  subtypeIRI TEXT,
  subtypeLiteral TEXT,
  tag TEXT,
  timeOfDay TEXT,
  title TEXT,
  variantDescription TEXT,
  variantIRI TEXT,
  variantLiteral TEXT,
  widthFrac NUMERIC,
  xFrac NUMERIC,
  yFrac NUMERIC
);

-- "behavior","caste","causeOfDeath","dataGeneralizations","dateIdentified",
-- "degreeOfEstablishment","establishmentMeans","eventID","externalClassificationSource",
-- "feedbackURL","identificationReferences","identificationRemarks",
-- "identificationVerificationStatus","identifiedBy","identifiedByID",
-- "informationWithheld","isPartOfOccurrenceID","lifeStage","occurrenceID",
-- "occurrenceReferences","occurrenceRemarks","occurrenceStatus","organismID",
-- "organismName","organismQuantity","organismQuantityType","organismRemarks",
-- "organismScope","pathway","recordedBy","recordedByID","reproductiveCondition",
-- "scientificName","scientificNameAuthorship","scientificNameID","sex","substrate",
-- "surveyTargetID","taxonID","taxonRank","verbatimIdentification","vernacularName",
-- "vitality"
CREATE TABLE input_occurrence (
  behavior TEXT,
  caste TEXT,
  causeOfDeath TEXT,
  dataGeneralizations TEXT,
  dateIdentified TEXT,
  degreeOfEstablishment TEXT,
  establishmentMeans TEXT,
  eventID TEXT NOT NULL,
  externalClassificationSource TEXT,
  feedbackURL TEXT,
  identificationReferences TEXT,
  identificationRemarks TEXT,
  identificationVerificationStatus TEXT,
  identifiedBy TEXT,
  identifiedByID TEXT,
  informationWithheld TEXT,
  isPartOfOccurrenceID TEXT,
  lifeStage TEXT,
  occurrenceID TEXT PRIMARY KEY NOT NULL,
  occurrenceReferences TEXT,
  occurrenceRemarks TEXT,
  occurrenceStatus TEXT,
  organismID TEXT,
  organismName TEXT,
  organismQuantity TEXT,
  organismQuantityType TEXT,
  organismRemarks TEXT,
  organismScope TEXT,
  pathway TEXT,
  recordedBy TEXT,
  recordedByID TEXT,
  reproductiveCondition TEXT,
  scientificName TEXT,
  scientificNameAuthorship TEXT,
  scientificNameID TEXT,
  sex TEXT,
  substrate TEXT,
  surveyTargetID TEXT,
  taxonID TEXT,
  taxonRank TEXT,
  verbatimIdentification TEXT,
  vernacularName TEXT,
  vitality TEXT
);

-- "accessRights","attributionLinkURL","attributionLogoURL","credit","license",
-- "licenseLogoURL","licensingException","owner","ownerID","rights","rightsHolder",
-- "rightsHolderID","rightsIRI","usagePolicyID","usageTerms","webStatement"
CREATE TABLE input_usage_policy (
  accessRights TEXT,
  attributionLinkURL TEXT,
  attributionLogoURL TEXT,
  credit TEXT,
  license TEXT,
  licenseLogoURL TEXT,
  licensingException TEXT,
  owner TEXT,
  ownerID TEXT,
  rights TEXT,
  rightsHolder TEXT,
  rightsHolderID TEXT,
  rightsIRI TEXT,
  usagePolicyID TEXT PRIMARY KEY NOT NULL,
  usageTerms TEXT,
  webStatement TEXT
);